name: ece447
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - pygraphviz
  - python-graphviz
  - seaborn
  - notebook
  - numpy
  - mlflow
  - ipywidgets
  - jupyterlab
  - tensorflow
  - optuna
